name: CI
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linter:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          ANSIBLE_DIRECTORY: playbooks
          VALIDATE_BASH: true
          VALIDATE_ANSIBLE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  scan_secure:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps: 
    - uses: actions/checkout@v4
    - name: semgrep
      run: semgrep --config auto 
     
