name: CI
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linter:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          ANSIBLE_DIRECTORY: playbooks
          VALIDATE_BASH: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: shellcheck
        run: |
          shellcheck attack_systems_scripts/*.sh
          shellcheck scripts_linux_ansible/*.sh
          shellcheck ArielRunVagrant.sh
          shellcheck /scripts_linux_ansible/KaliConfSofts/*.sh
  
  scan_secure:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: semgrep-action
      uses: returntocorp/semgrep-action@v1
    - name: semgrep
      run: semgrep --config auto 
     
